<?php

declare(strict_types=1);

namespace Biga\FieldEncryptionBundle\Command;

use Biga\FieldEncryptionBundle\Service\FieldEncryptionService;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

/**
 * Console command to generate a secure encryption key for the FieldEncryptionBundle.
 *
 * Usage:
 *     php bin/console field-encryption:generate-key
 *     php bin/console field-encryption:generate-key --env-format
 *     php bin/console field-encryption:generate-key --append-to-env
 *
 * @author Bíró Gábor (biga156)
 */
#[AsCommand(
    name: 'field-encryption:generate-key',
    description: 'Generate a secure encryption key for field encryption',
)]
class GenerateEncryptionKeyCommand extends Command
{
    protected function configure(): void
    {
        $this
            ->addOption(
                'env-format',
                'f',
                InputOption::VALUE_NONE,
                'Output in .env format (FIELD_ENCRYPTION_KEY=...)'
            )
            ->addOption(
                'append-to-env',
                'a',
                InputOption::VALUE_NONE,
                'Append the key to the .env.local file (creates if not exists)'
            )
            ->setHelp(<<<'HELP'
The <info>%command.name%</info> command generates a cryptographically secure
encryption key suitable for use with the FieldEncryptionBundle.

Generate a key and display it:
    <info>php %command.full_name%</info>

Generate a key in .env format:
    <info>php %command.full_name% --env-format</info>

Generate and append to .env.local:
    <info>php %command.full_name% --append-to-env</info>

The generated key is a 64-character hexadecimal string (256 bits).
Store this key securely - losing it means losing access to encrypted data!
HELP);
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);

        $key = FieldEncryptionService::generateKey();

        if ($input->getOption('append-to-env')) {
            return $this->appendToEnvFile($io, $key);
        }

        if ($input->getOption('env-format')) {
            $output->writeln(sprintf('FIELD_ENCRYPTION_KEY=%s', $key));
        } else {
            $io->success('Generated encryption key:');
            $output->writeln($key);
            $io->newLine();
            $io->note([
                'Add this to your .env.local file:',
                sprintf('FIELD_ENCRYPTION_KEY=%s', $key),
            ]);
        }

        $io->warning([
            'Store this key securely!',
            'Losing the encryption key means losing access to all encrypted data.',
            'Never commit encryption keys to version control.',
        ]);

        return Command::SUCCESS;
    }

    private function appendToEnvFile(SymfonyStyle $io, string $key): int
    {
        $projectDir  = $this->getProjectDir();
        $envFilePath = $projectDir . '/.env.local';

        $envLine = sprintf("\n# Generated by field-encryption:generate-key on %s\nFIELD_ENCRYPTION_KEY=%s\n", date('Y-m-d H:i:s'), $key);

        // Check if the file already contains a FIELD_ENCRYPTION_KEY
        if (file_exists($envFilePath)) {
            $contents = file_get_contents($envFilePath);
            if (str_contains($contents, 'FIELD_ENCRYPTION_KEY=')) {
                $io->error('FIELD_ENCRYPTION_KEY already exists in .env.local. Remove it first if you want to generate a new key.');

                return Command::FAILURE;
            }
        }

        if (false === file_put_contents($envFilePath, $envLine, \FILE_APPEND)) {
            $io->error(sprintf('Failed to write to %s', $envFilePath));

            return Command::FAILURE;
        }

        $io->success([
            'Encryption key generated and appended to .env.local',
            sprintf('Key: %s', $key),
        ]);

        $io->warning([
            'Store this key securely!',
            'Losing the encryption key means losing access to all encrypted data.',
            'Make sure .env.local is in your .gitignore!',
        ]);

        return Command::SUCCESS;
    }

    private function getProjectDir(): string
    {
        // Try to find the project directory by looking for composer.json
        $dir = getcwd() ?: __DIR__;
        while ('/' !== $dir && !file_exists($dir . '/composer.json')) {
            $dir = \dirname($dir);
        }

        return $dir;
    }
}
